import React from 'react';import{createRoot}from'react-dom/client';import{ArrowRight,Search,CalendarDays,MapPin,Clock,Check,ChevronRight}from'lucide-react';import'./styles.css';
const A=({children,ghost=false,href="#product"})=><a className={'button '+(ghost?'ghost':'')} href={href}>{children}<ArrowRight size={15}/></a>;
const Brand=()=> <a className="brand" href="#"><strong>NXLVL</strong><span>TRAINING</span></a>;
function Finder(){return <div className="finder"><div className="appbar"><Brand/><span>PLAYER MODE</span><b>PV</b></div><div className="appgrid"><aside><i>01</i><strong>Discover</strong><span>Sessions</span><span>Development</span><span>Profile</span></aside><div className="appmain"><div className="micro">PRIVATE COACHES / UTAH</div><div className="apptitle">Find your next session.</div><div className="search"><Search size={15}/><span>Coach, skill or location</span><kbd>⌘ K</kbd></div><div className="filterrow"><b>Recommended</b><span>Technical</span><span>Finishing</span><span>Speed</span></div>{[['MC','Mateo Cruz','Technical · 1v1','Orem, UT'],['JR','Jordan Reed','Finishing · Attack','Provo, UT'],['DS','Diego Santos','Speed · Movement','Lehi, UT']].map((x,i)=><div className="result" key={x[1]}><div className={'initial '+(i===0?'hot':'')}>{x[0]}</div><div><strong>{x[1]}</strong><small>{x[2]}</small></div><span><MapPin size={11}/>{x[3]}</span><ChevronRight size={16}/></div>)}</div></div></div>}
function Session(){return <div className="session"><div className="micro">NEXT SESSION</div><div className="sessiontop"><div><h3>Technical<br/>Development</h3><span>Private · 60 min</span></div><b>CONFIRMED</b></div><div className="person"><div className="initial hot">MC</div><div><strong>Mateo Cruz</strong><small>Private Coach</small></div></div><div className="facts"><span><CalendarDays/>SAT, OCT 03</span><span><Clock/>10:00 AM</span><span><MapPin/>OREM, UTAH</span></div><button>VIEW SESSION <ArrowRight size={14}/></button></div>}
function CoachDesk(){return <div className="desk"><div className="deskhead"><div><span>COACH DASHBOARD</span><h3>Saturday</h3></div><b>03 OCT</b></div>{[['09:00','Lucas M.','Technical'],['11:00','Ethan R.','Finishing'],['16:30','Noah S.','1v1 / Speed']].map((x,i)=><div className="slot" key={x[0]}><time>{x[0]}</time><div><strong>{x[1]}</strong><small>{x[2]}</small></div><span>{i?'UPCOMING':'COMPLETE'}</span></div>)}<div className="task"><div><span>POST-SESSION</span><strong>Lucas is waiting for feedback.</strong></div><button>ADD FEEDBACK <ArrowRight size={13}/></button></div></div>}
function Report(){return <div className="report"><div className="reporthead"><span>SESSION 014</span><b>COACH FEEDBACK</b><span>SEP 22</span></div><h3>Technical Development</h3><p>Mateo Cruz · Private Coach</p>{[['FIRST TOUCH',82],['1V1',76],['FINISHING',69]].map(x=><div className="metric" key={x[0]}><span>{x[0]}</span><div><i style={{width:x[1]+'%'}}/></div><b>{(x[1]/10).toFixed(1)}</b></div>)}<blockquote>Good progress receiving under pressure. Next session: finishing after the first touch.</blockquote></div>}
function App(){return <><header><Brand/><nav><a href="#how">How it works</a><a href="#players">Players</a><a href="#coaches">Coaches</a></nav><A href="#players">Find a coach</A></header>
<main><section className="hero"><div className="heroText"><div className="kicker"><span/>PRIVATE SOCCER TRAINING</div><h1>Find a coach.<br/><em>Do the work.</em><br/>See the progress.</h1><p>NXLVL puts private coaching, booking and player feedback into one clear development record.</p><div className="actions"><A href="#players">Find a coach</A><A ghost href="#coaches">I'm a coach</A></div><small>BUILT FOR SOCCER. BUILT AROUND THE SESSION.</small></div><Finder/></section>
<section id="how" className="rail"><div><i>01</i><b>DISCOVER</b><span>Find the right coach.</span></div><div><i>02</i><b>BOOK</b><span>Choose a session.</span></div><div><i>03</i><b>TRAIN</b><span>Show up. Do the work.</span></div><div><i>04</i><b>FEEDBACK</b><span>Know what comes next.</span></div><div><i>05</i><b>DEVELOP</b><span>Build the record.</span></div></section>
<section className="manifesto"><span>PRIVATE TRAINING, CONNECTED.</span><h2>A booking is one hour.<br/><em>Development is everything around it.</em></h2><div><p>Players shouldn't lose the value of a session the moment they leave the field.</p><p>Coaches shouldn't need five different tools to run private training.</p></div></section>
<section id="players" className="feature dark"><div className="copy"><span className="index">01 — FOR PLAYERS</span><h2>Know who you're training with. Know what you're working on.</h2><p>Search for private coaches, book around your schedule and keep the coach's feedback attached to your development.</p><ul><li><Check/>Coach discovery</li><li><Check/>Availability & booking</li><li><Check/>Session history</li><li><Check/>Structured feedback</li></ul><A href="#product">Player experience</A></div><Session/></section>
<section id="coaches" className="feature light"><CoachDesk/><div className="copy"><span className="index">02 — FOR COACHES</span><h2>Less admin between sessions. More focus on the player.</h2><p>Give players one place to find you, see availability and book. Keep attendance and post-session feedback connected to each player.</p><ul><li><Check/>Coach profile & discovery</li><li><Check/>Availability</li><li><Check/>Booking management</li><li><Check/>Attendance & feedback</li></ul><A href="#final">Coach with NXLVL</A></div></section>
<section id="product" className="feedbackSection"><div className="feedbackCopy"><span>03 — THE DIFFERENCE</span><h2>The session ends.<br/>The information doesn't.</h2><p>Each completed session can become part of a player's development history — not another message buried in a chat.</p></div><Report/></section>
<section id="final" className="final"><div className="kicker"><span/>NXLVL TRAINING</div><h2>TRAIN WITH<br/><em>INTENTION.</em></h2><p>Find the coach. Book the work. Keep the feedback. Build from there.</p><div className="actions"><A href="#players">Start training</A><A ghost href="#coaches">Become a coach</A></div></section></main>
<footer><Brand/><p>Private soccer training, organized around development.</p><div><a href="#players">Players</a><a href="#coaches">Coaches</a><a href="#how">How it works</a></div><small>© 2026 NXLVL Sports LLC</small></footer></>}
createRoot(document.getElementById('root')).render(<App/>);