import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{ArrowRight,Play,Search,CalendarDays,MapPin,Check}from'lucide-react';import'./styles.css';
const Brand=()=> <a className="brand" href="#"><b>NXLVL</b><span>TRAINING</span></a>;
const Btn=({children,light=false,href="#experience"})=><a className={'btn '+(light?'light':'')} href={href}>{children}<ArrowRight size={14}/></a>;
function Phone(){return <div className="phone"><div className="phoneTop"><span>9:41</span><b>NXLVL</b><i/></div><div className="phoneBody"><small>GOOD MORNING</small><h3>Ready for your<br/>next level?</h3><div className="progress"><div><strong>04</strong><span>SESSIONS</span></div><div><strong>03</strong><span>COACH NOTES</span></div></div><div className="next"><span>NEXT SESSION</span><b>Technical Development</b><small><CalendarDays/> Saturday · 10:00 AM</small><small><MapPin/> Orem, Utah</small></div><div className="phoneNav"><b>HOME</b><span>COACHES</span><span>PROGRESS</span></div></div></div>}
function App(){const[loaded,setLoaded]=useState(false);useEffect(()=>{const t=setTimeout(()=>setLoaded(true),1450);return()=>clearTimeout(t)},[]);return <div className={loaded?'site loaded':'site'}><div className="loader"><div className="loaderBrand">NXLVL</div><div className="loadline"><i/></div><span>TRAINING / DEVELOPMENT</span></div><header><Brand/><nav><a href="#about">About</a><a href="#experience">Experience</a><a href="#players">Players</a><a href="#coaches">Coaches</a></nav><Btn href="#experience">Explore NXLVL</Btn></header><main>
<section className="hero"><div className="ambient"/><div className="heroCopy"><span className="overline">PRIVATE SOCCER DEVELOPMENT</span><h1>Train with<br/>purpose.</h1><p>Find the right private coach, book your work and turn every session into a development record.</p><div className="heroBtns"><Btn light href="#experience">Start with NXLVL</Btn><a className="textBtn" href="#about"><Play size={12} fill="currentColor"/>How it works</a></div><div className="heroMeta"><span>FOR PLAYERS</span><span>FOR COACHES</span><span>BUILT FOR SOCCER</span></div></div><div className="deviceStage"><div className="halo"/><Phone/></div><div className="scroll">SCROLL TO EXPLORE <i/></div></section>
<section id="about" className="intro reveal"><span>01 / THE IDEA</span><h2>Private training should<br/>build into something.</h2><p>NXLVL connects the moments that are usually scattered: finding a coach, scheduling the session, doing the work and understanding what comes next.</p></section>
<section id="experience" className="dimensions"><div className="sticky"><span>02 / THE EXPERIENCE</span><h2>One place.<br/>Every session.</h2><p>A continuous path from discovery to development.</p></div><div className="dimensionList">{[['01','DISCOVER','Find coaches based on the work you need.'],['02','BOOK','See availability and choose the right session.'],['03','TRAIN','Show up with a clear purpose.'],['04','FEEDBACK','Keep the coach’s notes after the session ends.'],['05','DEVELOP','Build a history of the work over time.']].map(x=><article key={x[0]}><i>{x[0]}</i><div><h3>{x[1]}</h3><p>{x[2]}</p></div><ArrowRight/></article>)}</div></section>
<section id="players" className="story playerStory"><div className="storyVisual"><div className="searchPanel"><span>FIND A COACH</span><h3>What do you want<br/>to improve?</h3><div className="searchBox"><Search size={16}/> Technical, finishing, speed...</div><div className="coachRow"><b>MC</b><div><strong>Mateo Cruz</strong><small>Technical · 1v1</small></div><span>OREM</span></div><div className="coachRow"><b>JR</b><div><strong>Jordan Reed</strong><small>Finishing · Attack</small></div><span>PROVO</span></div></div></div><div className="storyCopy"><span>03 / FOR PLAYERS</span><h2>Know the work.<br/>See the progress.</h2><p>Your session shouldn't vanish into a text thread. Keep bookings, session history and coach feedback together.</p><ul><li><Check/>Find private soccer coaches</li><li><Check/>Book around your schedule</li><li><Check/>Keep post-session feedback</li></ul><Btn href="#final">Find your coach</Btn></div></section>
<section id="coaches" className="story coachStory"><div className="storyCopy"><span>04 / FOR COACHES</span><h2>Coach more.<br/>Manage less.</h2><p>Give private clients a professional path to discover you, book you and receive feedback — without running everything through scattered messages.</p><ul><li><Check/>Profile and discovery</li><li><Check/>Availability and bookings</li><li><Check/>Attendance and feedback</li></ul><Btn light href="#final">Join as a coach</Btn></div><div className="storyVisual darkVisual"><div className="schedule"><span>SATURDAY / 03 OCT</span><h3>3 sessions</h3>{[['09:00','Lucas M.','Technical'],['11:00','Ethan R.','Finishing'],['16:30','Noah S.','1v1 / Speed']].map(x=><div className="slot"><b>{x[0]}</b><div><strong>{x[1]}</strong><small>{x[2]}</small></div><i>→</i></div>)}</div></div></section>
<section className="statement"><span>05 / DEVELOPMENT</span><h2>The session ends.<br/><em>The development continues.</em></h2><p>Every booking can become context for the next one. Every note can become part of a bigger picture.</p></section>
<section id="final" className="final"><div className="finalOrb"/><span>NXLVL TRAINING</span><h2>Start from<br/>the work.</h2><p>Find your coach. Train with intention. Keep moving forward.</p><div><Btn light>Start training</Btn><a href="#coaches">I’m a coach <ArrowRight size={13}/></a></div></section></main><footer><Brand/><span>PRIVATE SOCCER TRAINING, CONNECTED.</span><div><a href="#players">Players</a><a href="#coaches">Coaches</a><a href="#about">About</a></div><small>© 2026 NXLVL SPORTS LLC</small></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);